### PR TITLE
Reboot the contributor guide

### LINKED ISSUE #18: Add a contributing guide
I am assigning @CircleCode since he started this few months ago.

### PR DESCRIPTION
**Pull request by Hywan**
Fix #18.

Progression:
  * [x] Introduction
  * [x] Prerequisites
      * [x] Tools
      * [x] Skills
      * [x] Getting help
  * [x] What to do?
      * [x] Boards for an overview
      * [x] What difficulty?
  * [x] Set up the environment
      * [x] Repository
      * [x] Dependencies
      * [x] New branch
  * [x] Validating a patch
      * [x] Preparing a patch
      * [x] Testing a patch
  * [x] Commiting a patch
    * [x] Review all your commits
  * [x] Publishing a patch
    * [x] Rebase when asked
    * [x] Reviewers
    * [x] Commiters
  * [x] Contributor pack
  * [x] Conclusion

Next progression:
  * [x] Review,
  * [ ] Preview,
  * [ ] Translate in French.

### CODE REVIEW

**Comment by Hywan** [comment]
TOC changed a little bit.

**Comment by Hywan** [comment]
TOC changed again.

**Comment by Hywan** [comment]
Contributor guide over. I will start a big review, then publish it on preview.hoa-project.net to ease your review. Finally, will translate it in French.

**Comment by Hywan** [comment]
Published here: http://hoa-project.net/En/Literature/Contributor/Guide.html.
Please review it @hoaproject/hoackers :smiley:!

**Comment by osaris** [comment]
Good job, I thought it would be could to have a more detailed part for "Validating a patch" but in fact, it's only writing a basic PHP file at the root folder of your fork and requiring the composer autoloader ... right ? Maybe we can add this at the beginning of the validating a patch section, I know it seems evident but It wasn't for me at the first time.

I will do a review for english syntax after we have discussed this.

**Comment by camael24** [comment]
I read fast, and i was good :) Nice Job :+1:

**Comment by Hywan** [comment]
@osaris Why not using tests instead?
@camael24 Thanks :smiley:.

**Comment by osaris** [comment]
@Hywan theoretically you are right, but for most of us it's really harder to write a test than to test with our own code because test involve preparing a lot of stuff.

**Comment by Hywan** [comment]
@osaris I am a little bit afraid that telling people to create a `foo.php` file that includes `vendor/autoload.php` and put everything inside sounds not too pro :-/. Isn't it?

**Comment by osaris** [comment]
@Hywan you are right BUT let me present it differently, I find a bug / something missing in a Hoa lib while working on a project that is using it. As I do my PR I want to be sure that my modification fix my problem on my bigger project. Make sense ?

**Comment by Hywan** [comment]
@osaris Probably yes. So, I will modify it to say: Either we write tests (see the `Hoa\Test` library) or you can create a simple `foo.php` file and bla bla bla. Would it be ok for you :smile:?

**Pull request merged**
